# Generated by Django 5.2.12 on 2026-03-11 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='detection_method',
            field=models.CharField(choices=[('NAKED_EYE', 'Naked Eye'), ('OPTICAL_AID', 'Optical Aid'), ('BINOCULARS', 'Binoculars'), ('TELESCOPE', 'Telescope'), ('CAMERA', 'Camera / CCD'), ('UNKNOWN', 'Unknown')], default='NAKED_EYE', max_length=20),
        ),
        migrations.AddField(
            model_name='observation',
            name='elevation_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='observation',
            name='observer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='observation',
            name='sky_condition',
            field=models.CharField(choices=[('CLEAR', 'Clear'), ('PARTLY_CLOUDY', 'Partly Cloudy'), ('HAZY', 'Hazy'), ('CLOUDY', 'Cloudy')], default='CLEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='observation',
            name='time_spent_searching_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='favouritelocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ObservationPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('verdict', models.CharField(max_length=20)),
                ('band', models.CharField(blank=True, max_length=10)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='moon.observation')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_alt_deg', models.FloatField(blank=True, null=True)),
                ('sun_az_deg', models.FloatField(blank=True, null=True)),
                ('moon_alt_deg', models.FloatField(blank=True, null=True)),
                ('moon_az_deg', models.FloatField(blank=True, null=True)),
                ('moon_distance_km', models.FloatField(blank=True, null=True)),
                ('elongation_deg', models.FloatField(blank=True, null=True)),
                ('daz_deg', models.FloatField(blank=True, null=True)),
                ('arcv_deg', models.FloatField(blank=True, null=True)),
                ('arcl_deg', models.FloatField(blank=True, null=True)),
                ('lag_minutes', models.IntegerField(blank=True, null=True)),
                ('moon_age_hours', models.FloatField(blank=True, null=True)),
                ('illumination_fraction', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='moon.observation')),
            ],
        ),
    ]
